In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(10)*5
# or
np.full((1,10), 5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [15]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.random.randn(1)

array([0.94030659])

In [30]:
np.random.randn(25)

array([-0.04064162, -0.48339834, -0.2899061 , -0.90629075, -0.72780858,
        0.04358893,  0.36099356,  1.84969354, -0.56538874, -0.91048345,
       -0.40870797,  0.32291238,  0.78896429, -0.59335856, -1.77658524,
        0.03317706,  1.54776186, -0.23165058, -0.17538606,  1.09175642,
       -0.19168735, -1.11488823,  0.24233796, -0.16431657, -0.69658211])

In [38]:
np.around([1.23,2.234,3],1)

array([1.2, 2.2, 3. ])

In [40]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [44]:
np.around(np.linspace(0, 1, 100).reshape(10, 10) , 2)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [45]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [54]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [71]:
arr = np.arange(12,24).reshape(3,4)

arr[1] += 1
arr[2] += 2
arr

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [77]:
np.arange(2,13, 5).reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [82]:
mat = np.arange(16, 26).reshape(2,5)

In [83]:
mat

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:
np.sum(mat)

205

In [85]:
np.std(mat)

2.8722813232690143

In [87]:
np.sum(mat, axis=0)

array([37, 39, 41, 43, 45])